version: "3.9"

services:
  api_gateway:
    build: ./apps/backend/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend/api_gateway:/app
    environment:
      - ENV=development
    depends_on:
      - journal_service

  postgres:
    image: postgres:15
    container_name: hermeticum_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hermeticum
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: journal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  journal_service:
    build:
      context: ./apps/backend/journal_service
    container_name: journal_service
    restart: always
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "8001:8001"
    volumes:
      - ./apps/backend/journal_service:/app
    env_file:
      - ./apps/backend/journal_service/.env
    depends_on:
      - postgres
  
  auth_service:
    build:
      context: ./apps/backend/auth_service
    container_name: auth_service
    ports:
      - "8002:8002"
    volumes:
      - ./apps/backend/auth_service:/app
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
    env_file:
      - ./apps/backend/auth_service/.env
    environment:
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json

volumes:
  postgres_data: