version: "3.9"

services:
  api_gateway:
    build: ./apps/backend/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend/api_gateway:/app
    environment:
      - ENV=development
