version: "3.9"

services:
  api_gateway:
    build: ./apps/backend/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend/api_gateway:/app
    environment:
      - ENV=development
      - JOURNAL_SERVICE_URL=http://journal_service:8001
      - AI_SERVICE_URL=http://ai_service:8003
    depends_on:
      - journal_service
      - ai_service
    networks:
      - hermeticum_network

  journal_service:
    build:
      context: ./apps/backend/journal_service
    container_name: journal_service
    restart: always
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "8001:8001"
    volumes:
      - ./apps/backend/journal_service:/app
    networks:
      - hermeticum_network
  
  ai_service:
    build: ./apps/backend/ai_service
    container_name: hermeticum_ai_service
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ./apps/backend/ai_service:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - hermeticum_network

networks:
  hermeticum_network: