version: "3.9"

services:
  api_gateway:
    build: ./apps/backend/api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend/api_gateway:/app
    environment:
      - ENV=development

  postgres:
    image: postgres:15
    container_name: hermeticum_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hermeticum
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: journal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  journal_service:
    build:
      context: ./apps/backend/journal_service
    container_name: journal_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://hermeticum:secretpassword@postgres/journal_db
    ports:
      - "8001:8001"

volumes:
  postgres_data:
